# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: prompthub.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'prompthub.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fprompthub.proto\x12\x02PB\"*\n\nAddRequest\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x0e\n\x06Prompt\x18\x02 \x01(\t\" \n\x0b\x41\x64\x64Response\x12\x11\n\tAddOutput\x18\x01 \x01(\t\"0\n\rUpdateRequest\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x11\n\tNewPrompt\x18\x02 \x01(\t\"&\n\x0eUpdateResponse\x12\x14\n\x0cUpdateOutput\x18\x01 \x01(\t\"\x1d\n\rDeleteRequest\x12\x0c\n\x04Name\x18\x01 \x01(\t\"&\n\x0e\x44\x65leteResponse\x12\x14\n\x0c\x44\x65leteOutput\x18\x01 \x01(\t\"\x1a\n\nGetRequest\x12\x0c\n\x04Name\x18\x01 \x01(\t\" \n\x0bGetResponse\x12\x11\n\tGetOutput\x18\x01 \x01(\t\"\r\n\x0bListRequest\"\"\n\x0cListResponse\x12\x12\n\nListOutput\x18\x01 \x01(\t\"\x1f\n\rSelectRequest\x12\x0e\n\x06Number\x18\x01 \x01(\t\"&\n\x0eSelectResponse\x12\x14\n\x0cSelectOutput\x18\x01 \x01(\t2\xa2\x02\n\x06simple\x12(\n\x03\x61\x64\x64\x12\x0e.PB.AddRequest\x1a\x0f.PB.AddResponse\"\x00\x12\x31\n\x06update\x12\x11.PB.UpdateRequest\x1a\x12.PB.UpdateResponse\"\x00\x12\x31\n\x06\x64\x65lete\x12\x11.PB.DeleteRequest\x1a\x12.PB.DeleteResponse\"\x00\x12(\n\x03get\x12\x0e.PB.GetRequest\x1a\x0f.PB.GetResponse\"\x00\x12+\n\x04list\x12\x0f.PB.ListRequest\x1a\x10.PB.ListResponse\"\x00\x12\x31\n\x06select\x12\x11.PB.SelectRequest\x1a\x12.PB.SelectResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prompthub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=23
  _globals['_ADDREQUEST']._serialized_end=65
  _globals['_ADDRESPONSE']._serialized_start=67
  _globals['_ADDRESPONSE']._serialized_end=99
  _globals['_UPDATEREQUEST']._serialized_start=101
  _globals['_UPDATEREQUEST']._serialized_end=149
  _globals['_UPDATERESPONSE']._serialized_start=151
  _globals['_UPDATERESPONSE']._serialized_end=189
  _globals['_DELETEREQUEST']._serialized_start=191
  _globals['_DELETEREQUEST']._serialized_end=220
  _globals['_DELETERESPONSE']._serialized_start=222
  _globals['_DELETERESPONSE']._serialized_end=260
  _globals['_GETREQUEST']._serialized_start=262
  _globals['_GETREQUEST']._serialized_end=288
  _globals['_GETRESPONSE']._serialized_start=290
  _globals['_GETRESPONSE']._serialized_end=322
  _globals['_LISTREQUEST']._serialized_start=324
  _globals['_LISTREQUEST']._serialized_end=337
  _globals['_LISTRESPONSE']._serialized_start=339
  _globals['_LISTRESPONSE']._serialized_end=373
  _globals['_SELECTREQUEST']._serialized_start=375
  _globals['_SELECTREQUEST']._serialized_end=406
  _globals['_SELECTRESPONSE']._serialized_start=408
  _globals['_SELECTRESPONSE']._serialized_end=446
  _globals['_SIMPLE']._serialized_start=449
  _globals['_SIMPLE']._serialized_end=739
# @@protoc_insertion_point(module_scope)
